name: Atualizar Dados da FPF

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Executar o scraper
        run: |
          python fetch_fpf.py

      - name: Gerar manifesto de emblemas
        run: |
          python generate_crest_manifest.py

      - name: Fazer commit e push das alterações
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/*.json || true
          git diff --staged --quiet || git commit -m "Update: dados FPF e emblemas" 
          git push || echo "Sem alterações para publicar"
